---
title: "Shiny Application and Reproducible Pitch"
author: "Ricardo Arango Giraldo"
date: "28 de octubre de 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Project

This peer assessed assignment has two parts. First, we will create a Shiny application and deploy it on Rstudio's servers. Second, we will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

## Application Summary

Puerto Ricans who were born in Puerto Rico are American citizens as if they were born in the states. At 10% of the Latino population in the United States, Puerto Ricans are the second-largest Latino group nationwide, after Mexican-Americans, and are 1.5% of the entire population of the United States. Although the 2010 Census counted the number of Puerto Ricans living in the United States at 4.6 million, estimates in 2012 show the Puerto Rican population to be over 5 million.

## The Repository

The repository consists of three final files:

ui.R
server.R
puertoricansinusa.csv

The ui.R and server.R are the code for the shiny application: https://github.com/riarangogi/myfirstappshiny

## Shiny Application

https://riarangogi.shinyapps.io/Shiny_First_app/